GET http://localhost:3000/videos
Content-Type: application/json
Accept: application/json
###
GET http://localhost:3000/videos/1
Content-Type: application/json
Accept: application/json
###
POST http://localhost:3000/videos
Content-Type: application/json
Accept: application/json

{
  "title": "My first video",
  "description": "This is a description",
  "url": "http://www.youtube.com/watch?v=1234567890"
}
###
POST http://localhost:3000/v1/courses
Content-Type: application/json
Accept: application/json

{
  # "title": "My first course",
  # "description": "This is a description",
  # "cover": "http://www.youtube.com/watch?v=1234567890",
  # "price": 9.99
}
###
GET http://localhost:3000/v1/courses/1
Content-Type: application/json
Accept: application/json
